# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
