# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saresep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
