# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saresep', '0002_auto_20170207_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
